# Generated by Django 4.2 on 2024-04-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='slug of the category', max_length=55, unique=True, verbose_name='slug of the category')),
                ('name', models.CharField(help_text='name of the category', max_length=55, unique=True, verbose_name='name of the category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='slug of the watch', max_length=55, unique=True, verbose_name='slug of the watch')),
                ('name', models.CharField(help_text='name of the watch', max_length=255, verbose_name='name watch')),
                ('description', models.TextField(help_text='description of the watch', verbose_name='description of the watch')),
                ('price_sell', models.PositiveIntegerField(verbose_name='price for customers')),
                ('price_buy', models.PositiveIntegerField(verbose_name='purchase price')),
                ('count', models.IntegerField(verbose_name='stock balance')),
            ],
        ),
    ]
