# Generated by Django 4.2 on 2024-04-12 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appwatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorywatch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appwatch.category'),
        ),
        migrations.AddField(
            model_name='categorywatch',
            name='watch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appwatch.watch'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_watch',
            field=models.ManyToManyField(through='appwatch.CategoryWatch', to='appwatch.watch'),
        ),
    ]
