# Generated by Django 4.2 on 2024-04-22 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appwatch', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='categorywatch',
            options={'verbose_name': 'CategoryWatch', 'verbose_name_plural': 'CategoryWatch'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'ShoppingCart', 'verbose_name_plural': 'ShoppingCarts'},
        ),
        migrations.AlterModelOptions(
            name='watch',
            options={'verbose_name': 'Watch', 'verbose_name_plural': 'Watches'},
        ),
    ]
