"""add table

Revision ID: a57a428c89b0
Revises: d351874f40b3
Create Date: 2024-03-21 01:01:27.550686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57a428c89b0'
down_revision: Union[str, None] = 'd351874f40b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('d_client',
    sa.Column('fio', sa.String(length=150), nullable=False, comment='full name client'),
    sa.Column('address', sa.String(length=150), nullable=False, comment='Client address for life'),
    sa.Column('phone', sa.String(length=15), nullable=False, comment='phone client'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('d_emploers',
    sa.Column('code', sa.String(length=50), nullable=False, comment='code employee'),
    sa.Column('firstname', sa.String(length=50), nullable=False, comment='first name employee'),
    sa.Column('surname', sa.String(length=50), nullable=False, comment='surname name employee'),
    sa.Column('lastname', sa.String(length=50), nullable=False, comment='lastname name employee'),
    sa.Column('jobtitle', sa.String(length=50), nullable=False, comment='jobtitle employee'),
    sa.Column('address', sa.String(length=150), nullable=False, comment='address to employee'),
    sa.Column('phone', sa.String(length=15), nullable=False, comment='phone to employee'),
    sa.Column('birthday', sa.Date(), nullable=False, comment='birthdate to employee'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('d_providers',
    sa.Column('code', sa.String(length=50), nullable=False, comment='provider code'),
    sa.Column('name_provider', sa.String(length=50), nullable=False, comment='provider name'),
    sa.Column('pred_provider', sa.String(length=50), nullable=False, comment="supplier's representative"),
    sa.Column('asked', sa.String(length=50), nullable=False, comment='name to contact'),
    sa.Column('address', sa.String(length=150), nullable=False, comment='address to provider'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('d_delivery',
    sa.Column('code', sa.String(length=50), nullable=False, comment='code delivery'),
    sa.Column('date_delivery', sa.Date(), nullable=False, comment='date delivery'),
    sa.Column('provider_id', sa.Integer(), nullable=False, comment='id to provider'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['d_providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('d_products',
    sa.Column('code', sa.String(length=50), nullable=False, comment='product code'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='name product'),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('cost_buy', sa.Integer(), nullable=False),
    sa.Column('is_existed', sa.Boolean(), nullable=False),
    sa.Column('cnt', sa.Integer(), nullable=False),
    sa.Column('cost_sell', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.Integer(), nullable=False, comment='id row for delivery'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['d_delivery.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('d_orders',
    sa.Column('code', sa.String(length=30), nullable=False, comment='code order'),
    sa.Column('date_placed', sa.Date(), nullable=False),
    sa.Column('date_executed', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False, comment='href of client'),
    sa.Column('emploer_id', sa.Integer(), nullable=False, comment='href of order'),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='href of product'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['d_client.id'], ),
    sa.ForeignKeyConstraint(['emploer_id'], ['d_emploers.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['d_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('employers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('code_emp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('jobtitle', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='employers_pkey')
    )
    op.drop_table('d_orders')
    op.drop_table('d_products')
    op.drop_table('d_delivery')
    op.drop_table('d_providers')
    op.drop_table('d_emploers')
    op.drop_table('d_client')
    # ### end Alembic commands ###
