"""add colum nullable

Revision ID: cde1d88a0c42
Revises: a57a428c89b0
Create Date: 2024-03-21 23:59:19.426218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cde1d88a0c42"
down_revision: Union[str, None] = "a57a428c89b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "d_delivery",
        "code",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="code delivery",
    )
    op.alter_column(
        "d_delivery",
        "date_delivery",
        existing_type=sa.DATE(),
        nullable=True,
        existing_comment="date delivery",
    )
    op.alter_column(
        "d_delivery",
        "provider_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="id to provider",
    )
    op.alter_column(
        "d_emploers",
        "code",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="code employee",
    )
    op.alter_column(
        "d_emploers",
        "firstname",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="first name employee",
    )
    op.alter_column(
        "d_emploers",
        "surname",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="surname name employee",
    )
    op.alter_column(
        "d_emploers",
        "lastname",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="lastname name employee",
    )
    op.alter_column(
        "d_emploers",
        "jobtitle",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="jobtitle employee",
    )
    op.alter_column(
        "d_emploers",
        "address",
        existing_type=sa.VARCHAR(length=150),
        nullable=True,
        existing_comment="address to employee",
    )
    op.alter_column(
        "d_emploers",
        "phone",
        existing_type=sa.VARCHAR(length=15),
        nullable=True,
        existing_comment="phone to employee",
    )
    op.alter_column(
        "d_orders",
        "code",
        existing_type=sa.VARCHAR(length=30),
        nullable=True,
        existing_comment="code order",
    )
    op.alter_column(
        "d_orders", "date_placed", existing_type=sa.DATE(), nullable=True
    )
    op.alter_column(
        "d_orders",
        "date_executed",
        existing_type=sa.DATE(),
        nullable=True,
        comment="test",
    )
    op.alter_column(
        "d_orders",
        "client_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="href of client",
    )
    op.alter_column(
        "d_orders",
        "emploer_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="href of order",
    )
    op.alter_column(
        "d_orders",
        "product_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="href of product",
    )
    op.alter_column(
        "d_products",
        "code",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="product code",
    )
    op.alter_column(
        "d_products",
        "name",
        existing_type=sa.VARCHAR(length=150),
        nullable=True,
        existing_comment="name product",
    )
    op.alter_column(
        "d_products", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "d_products", "cost_buy", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "d_products", "is_existed", existing_type=sa.BOOLEAN(), nullable=True
    )
    op.alter_column(
        "d_products", "cnt", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "d_products", "cost_sell", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "d_products",
        "delivery_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="id row for delivery",
    )
    op.alter_column(
        "d_providers",
        "name_provider",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="provider name",
    )
    op.alter_column(
        "d_providers",
        "pred_provider",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="supplier's representative",
    )
    op.alter_column(
        "d_providers",
        "asked",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
        existing_comment="name to contact",
    )
    op.alter_column(
        "d_providers",
        "address",
        existing_type=sa.VARCHAR(length=150),
        nullable=True,
        existing_comment="address to provider",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "d_providers",
        "address",
        existing_type=sa.VARCHAR(length=150),
        nullable=False,
        existing_comment="address to provider",
    )
    op.alter_column(
        "d_providers",
        "asked",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="name to contact",
    )
    op.alter_column(
        "d_providers",
        "pred_provider",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="supplier's representative",
    )
    op.alter_column(
        "d_providers",
        "name_provider",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="provider name",
    )
    op.alter_column(
        "d_products",
        "delivery_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="id row for delivery",
    )
    op.alter_column(
        "d_products", "cost_sell", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "d_products", "cnt", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "d_products", "is_existed", existing_type=sa.BOOLEAN(), nullable=False
    )
    op.alter_column(
        "d_products", "cost_buy", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "d_products", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "d_products",
        "name",
        existing_type=sa.VARCHAR(length=150),
        nullable=False,
        existing_comment="name product",
    )
    op.alter_column(
        "d_products",
        "code",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="product code",
    )
    op.alter_column(
        "d_orders",
        "product_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="href of product",
    )
    op.alter_column(
        "d_orders",
        "emploer_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="href of order",
    )
    op.alter_column(
        "d_orders",
        "client_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="href of client",
    )
    op.alter_column(
        "d_orders",
        "date_executed",
        existing_type=sa.DATE(),
        nullable=False,
        comment=None,
        existing_comment="test",
    )
    op.alter_column(
        "d_orders", "date_placed", existing_type=sa.DATE(), nullable=False
    )
    op.alter_column(
        "d_orders",
        "code",
        existing_type=sa.VARCHAR(length=30),
        nullable=False,
        existing_comment="code order",
    )
    op.alter_column(
        "d_emploers",
        "phone",
        existing_type=sa.VARCHAR(length=15),
        nullable=False,
        existing_comment="phone to employee",
    )
    op.alter_column(
        "d_emploers",
        "address",
        existing_type=sa.VARCHAR(length=150),
        nullable=False,
        existing_comment="address to employee",
    )
    op.alter_column(
        "d_emploers",
        "jobtitle",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="jobtitle employee",
    )
    op.alter_column(
        "d_emploers",
        "lastname",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="lastname name employee",
    )
    op.alter_column(
        "d_emploers",
        "surname",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="surname name employee",
    )
    op.alter_column(
        "d_emploers",
        "firstname",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="first name employee",
    )
    op.alter_column(
        "d_emploers",
        "code",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="code employee",
    )
    op.alter_column(
        "d_delivery",
        "provider_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="id to provider",
    )
    op.alter_column(
        "d_delivery",
        "date_delivery",
        existing_type=sa.DATE(),
        nullable=False,
        existing_comment="date delivery",
    )
    op.alter_column(
        "d_delivery",
        "code",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
        existing_comment="code delivery",
    )
    # ### end Alembic commands ###
