version: '3'

services:

  app:
    build:
      context: .
    container_name: app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/app/src
      - ./documents:/app/documents/
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - db

  db:
    image: postgres:15
    container_name: db_app
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq_app
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A src.tasks:celery worker --loglevel=info
    volumes:
      - ./documents:/app/documents/
    depends_on:
      - rabbitmq

  migrate:
    build:
      context: .
    container_name: migrate
    command: alembic upgrade head
    depends_on:
      - db
      - app
